version: '3.0'
services:
  # port required: 7000 | 7500 | 7080
  dev-filebeat:
    image: registry.cn-shanghai.aliyuncs.com/alice52/xx:xx
    restart: 'always'
    container_name: dev-filebeat
    environment:
      TZ: Asia/Shanghai
      BEATS_SYSTEM_PASSWORD: x
      PROJECT_NAME: x
      PROJECT_LOG_DIR: x
      OUTPUT_ES: x
      ES_HOST: x
      FILEBEAT_INTERNAL_PASSWORD: x
      OUTPUT_LS: x
      LS_HOST: x
      LS_PORT: x
