version: '2.2'
services:
  activemq:
    image: registry.cn-shanghai.aliyuncs.com/alice52/dev-activemq:20200412.3c824a8
    restart: 'no'
    container_name: dev-activemq
    ports:
      - 8161:8161
      - 61613:61613
    volumes:
      - /root/activemq/data:/data/activemq
      - /root/activemq/logs:/var/log/activemq
    environment:
      TZ: Asia/Shanghai
